[package]
name = "boo-hoo"
description = "An implementation of ZKBoo"
repository = "https://github.com/cronokirby/boo-hoo"
license = "MIT"
version = "0.2.0"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.1"
blake3 = "1.3.1"
rand_core = "0.6.3"

[dev-dependencies]
proptest = "1.0.0"
