[package]
name = "boo-hoo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.1"
blake3 = "1.3.1"
rand_core = "0.6.3"

[dev-dependencies]
proptest = "1.0.0"
